apiVersion: v1
kind: Namespace
metadata:
  name: wwte
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwte-deployment
  namespace: wwte
  labels: 
    app: wwte-app
spec:
  selector:
    matchLabels:
      app: wwte-app
  replicas: 2
  template:
    metadata:
      labels: 
        app: wwte-app
      namespace: wwte
    spec: 
      containers:
      - name: wwte-app
        image: ghcr.io/bapt0u/whenwillthisend:main
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: lb-wwte
  namespace: wwte
spec:
  type: LoadBalancer
  selector:
    app: wwte-app
  ports:
    - name: http
      protocol: TCP
      port: 80
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-wwte
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: wwte
  rules: 
  - host: wwte.example.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: lb-wwte
            port:
              number: 80